import buildURL from './buildUrl'
import parseHeaders from './parseHeaders'
import isURLSameOrigin from './isURLSameOrigin'
import cookies from './cookies'
import { forEach } from './utils'
import { AxiosTransformer } from '../type'